### PR TITLE
Fix check-inodes.sh script.

### PR DESCRIPTION
**Pull request by jeffmcutter**
Output from running analysis role:
```
line 36: badinitio: unbound variable
```

Output testing script manually:
```
[root@satrhel6-1 ~]# /tmp/check-inodes.sh 
/tmp/check-inodes.sh: line 36: badinitio: unbound variable
[root@satrhel6-1 ~]# bash /tmp/check-inodes.sh 
/tmp/check-inodes.sh: line 36: exit: : numeric argument required
```

### CODE REVIEW

**Comment by jeffmcutter** [comment]
@djdanielsson Can you look at this one?  https://github.com/redhat-cop/infra.leapp/pull/202 broke check-inodes.sh (see description above).  Thanks!

**Review by djdanielsson — APPROVED** [review]
Hum... I wondered if those changes would break it. I will have to figure out how to make it skip this in sanity check

**Review by djdanielsson — CHANGES_REQUESTED** [review]
I'll try and fix this

**Review by swapdisk — COMMENTED** [review]
The "unbound variable" error is because `$badinitio` is unset if the report shortfalls loop doesn't find any problems. It was fine until `-u` bash option was added. Per bash man page, that option tells bash to treat unset variables as an error...
```
-u   Treat unset variables and parameters other than the special para‐
     meters "@" and "*", or array variables subscripted  with  "@"  or
     "*",  as an error when performing parameter expansion.  If expan‐
     sion is attempted on an unset variable or  parameter,  the  shell
     prints  an  error  message, and, if not interactive, exits with a
     non-zero status.
```
Let me recommend we just add `badinitio=0` before the loop at line 23 and we should be able to leave everything else as it was and not need to do the sanity test ignores.

**Comment by djdanielsson** [comment]
yep I figured that out and did just that

**Review by swapdisk — APPROVED** [review]

**Review by djdanielsson — APPROVED** [review]

**Comment by jeffmcutter** [comment]
Pulled the latest main and ran analysis successfully on a RHEL 6 box.  :-)

**Pull request merged**
