### PR TITLE
Collect inhibitor and high not enough space on RHEL 6.

### PR DESCRIPTION
**Pull request by jeffmcutter**
For inclusion into summary output and saving into leapp_inhibitors artifact.

### CODE REVIEW

**Comment by jeffmcutter** [comment]
Sample RHEL 6-7 analysis with EXTREME (inhibitor) and HIGH not enough space:

```
RUNNING HANDLER [infra.leapp.analysis : Display inhibitors] ********************
ok: [satrhel6-1.localdomain.local] => {
    "results_inhibitors.stdout_lines": [
        "preupg.risk.EXTREME: The /usr/ directory is located on a separate partition. The in-place upgrade is not possible."
    ]
}
Thursday 25 April 2024  11:04:01 +0000 (0:00:00.052)       0:04:01.701 ******** 
 [started HANDLER: infra.leapp.analysis : Display errors on satrhel6-1.localdomain.local]

RUNNING HANDLER [infra.leapp.analysis : Display errors] ************************
ok: [satrhel6-1.localdomain.local] => {
    "results_errors.stdout_lines": [
        "preupg.risk.HIGH: There is not enough free space in /usr for migration!",
        "preupg.risk.HIGH: There is not enough free space in /var for migration!",
        "preupg.risk.HIGH: Not enough free space on the /boot. Release more space for upgrade."
    ]
}
Thursday 25 April 2024  11:04:01 +0000 (0:00:00.067)       0:04:01.769 ******** 
 [started HANDLER: infra.leapp.analysis : Preupgrade analysis report is done on satrhel6-1.localdomain.local]

RUNNING HANDLER [infra.leapp.analysis : Preupgrade analysis report is done] ****
ok: [satrhel6-1.localdomain.local] => {
    "msg": "The preupgrade analysis report generation is now complete. WARNING: Inhibitors found. Review the tasks above or the result file at /root/preupgrade/result.txt."
```

**Comment by jeffmcutter** [comment]
Sample 6-7 where there are no inhibitors (EXTREME), but there are HIGH not enough space warnings, and so marked as inhibited:

```
RUNNING HANDLER [infra.leapp.analysis : Display inhibitors] ********************
skipping: [satrhel6-2.localdomain.local]
Thursday 25 April 2024  11:25:49 +0000 (0:00:00.037)       0:05:01.110 ******** 
 [started HANDLER: infra.leapp.analysis : Display errors on satrhel6-2.localdomain.local]

RUNNING HANDLER [infra.leapp.analysis : Display errors] ************************
ok: [satrhel6-2.localdomain.local] => {
    "results_errors.stdout_lines": [
        "preupg.risk.HIGH: Not enough free space on the /boot. Release more space for upgrade."
    ]
}
Thursday 25 April 2024  11:25:49 +0000 (0:00:00.047)       0:05:01.157 ******** 
 [started HANDLER: infra.leapp.analysis : Preupgrade analysis report is done on satrhel6-2.localdomain.local]

RUNNING HANDLER [infra.leapp.analysis : Preupgrade analysis report is done] ****
ok: [satrhel6-2.localdomain.local] => {
    "msg": "The preupgrade analysis report generation is now complete. WARNING: Inhibitors found. Review the tasks above or the result file at /root/preupgrade/result.txt."
}
```

**Comment by jeffmcutter** [comment]
A 7-8 Leapp one for comparison:

```
RUNNING HANDLER [infra.leapp.analysis : Display inhibitors] ********************
skipping: [satrhel7-1.localdomain.local]
Thursday 25 April 2024  11:03:20 +0000 (0:00:00.052)       0:03:12.163 ******** 
 [started HANDLER: infra.leapp.analysis : Display errors on satrhel7-1.localdomain.local]

RUNNING HANDLER [infra.leapp.analysis : Display errors] ************************
ok: [satrhel7-1.localdomain.local] => {
    "results_errors.stdout_lines": [
        "Risk Factor: high (error)",
        "Title: Not enough space available on /var/lib/leapp/scratch: Needed at least 3591 MiB.",
        "Summary: {\"detail\": \"The file system hosting the /var/lib/leapp/scratch directory does not contain enough free space to proceed all parts of the in-place upgrade. Note the calculated required free space is the minimum derived from upgrades of minimal systems and the actual needed free space could be higher.\\nNeeded at least: 3591 MiB.\\nSuggested free space: 4591 MiB (or more).\"}",
        "Key: 6469b14a9772e9987c08c637e415d1724c425cfa",
        "----------------------------------------"
    ]
}
Thursday 25 April 2024  11:03:20 +0000 (0:00:00.051)       0:03:12.214 ******** 
 [started HANDLER: infra.leapp.analysis : Preupgrade analysis report is done on satrhel7-1.localdomain.local]

RUNNING HANDLER [infra.leapp.analysis : Preupgrade analysis report is done] ****
ok: [satrhel7-1.localdomain.local] => {
    "msg": "The preupgrade analysis report generation is now complete. WARNING: Inhibitors found. Review the tasks above or the result file at /var/log/leapp/leapp-report.txt."
}
```

**Comment by jeffmcutter** [comment]
And an 8-9 Leapp one for comparison:

```
RUNNING HANDLER [infra.leapp.analysis : Display inhibitors] ***************************************************************************************************
ok: [satrhel8-1.localdomain.local] => {
    "results_inhibitors.stdout_lines": [
        "Risk Factor: high (inhibitor)",
        "Title: The installed OS version is not supported for the in-place upgrade to the target RHEL version",
        "Summary: The supported OS releases for the upgrade process:",
        " RHEL 8.6",
        "RHEL 8.8",
        "RHEL-SAPHANA 8.6",
        "RHEL-SAPHANA 8.8",
        "Key: 1c7a98849a747ec9890f04bf4321de7280970715",
        "----------------------------------------"
    ]
}
Thursday 25 April 2024  19:03:12 +0800 (0:00:00.051)       0:03:03.086 ******** 
 [started HANDLER: infra.leapp.analysis : Display errors on satrhel8-1.localdomain.local]

RUNNING HANDLER [infra.leapp.analysis : Display errors] *******************************************************************************************************
skipping: [satrhel8-1.localdomain.local]
Thursday 25 April 2024  19:03:12 +0800 (0:00:00.040)       0:03:03.126 ******** 
 [started HANDLER: infra.leapp.analysis : Preupgrade analysis report is done on satrhel8-1.localdomain.local]

RUNNING HANDLER [infra.leapp.analysis : Preupgrade analysis report is done] ***********************************************************************************
ok: [satrhel8-1.localdomain.local] => {
    "msg": "The preupgrade analysis report generation is now complete. WARNING: Inhibitors found. Review the tasks above or the result file at /var/log/leapp/leapp-report.txt."
}
```

**Review by djdanielsson — APPROVED** [review]
I like making it closer to be the same, the one question I have is, the High seems only related to free space, is that correct?

**Comment by jeffmcutter** [comment]
> I like making it closer to be the same, the one question I have is, the High seems only related to free space, is that correct?

There are a bunch of highs, the only ones that seem to matter are out of space ones.

**Pull request merged**
